
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import Project.connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sedhu
 */
public class displaydetails extends javax.swing.JFrame {

    /**
     * Creates new form displaydetails
     */
    public displaydetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTable20 = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jTabbedPane22 = new javax.swing.JTabbedPane();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jTabbedPane9 = new javax.swing.JTabbedPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jTabbedPane25 = new javax.swing.JTabbedPane();
        jScrollPane25 = new javax.swing.JScrollPane();
        jTable25 = new javax.swing.JTable();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable11 = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable();
        jTabbedPane19 = new javax.swing.JTabbedPane();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTable23 = new javax.swing.JTable();
        jTabbedPane24 = new javax.swing.JTabbedPane();
        jTabbedPane12 = new javax.swing.JTabbedPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable14 = new javax.swing.JTable();
        jTabbedPane13 = new javax.swing.JTabbedPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTable15 = new javax.swing.JTable();
        jTabbedPane15 = new javax.swing.JTabbedPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTable17 = new javax.swing.JTable();
        jTabbedPane14 = new javax.swing.JTabbedPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable16 = new javax.swing.JTable();
        jTabbedPane18 = new javax.swing.JTabbedPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTable21 = new javax.swing.JTable();
        jTabbedPane20 = new javax.swing.JTabbedPane();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTable22 = new javax.swing.JTable();
        jTabbedPane21 = new javax.swing.JTabbedPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTable19 = new javax.swing.JTable();
        jTabbedPane16 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jTabbedPane17 = new javax.swing.JTabbedPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTable18 = new javax.swing.JTable();
        jTabbedPane23 = new javax.swing.JTabbedPane();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTable24 = new javax.swing.JTable();
        jTabbedPane11 = new javax.swing.JTabbedPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        jTabbedPane26 = new javax.swing.JTabbedPane();
        jScrollPane26 = new javax.swing.JScrollPane();
        jTable26 = new javax.swing.JTable();
        jTabbedPane27 = new javax.swing.JTabbedPane();
        jScrollPane27 = new javax.swing.JScrollPane();
        jTable27 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CONUCTNUM", "DISEASE", "DURATIONS"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        setVisible(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setToolTipText("doctoravailable");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "DOB", "AONDUCTNUMBER", "BLOODGROUP", "GENDER", "ADDRESS", "PROBLEM"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("patientsdetails", jPanel2);

        jLabel1.setText("jLabel1");

        jTable20.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CONDUCTNUMBER", "DURATION", "DISEASES"
            }
        ));
        jScrollPane20.setViewportView(jTable20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 1704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("nward1", jPanel1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CONDUCTNUMBER", "DISEASES", "DURATION"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTabbedPane2.addTab("tab1", jScrollPane3);

        jTabbedPane1.addTab("nward2", jTabbedPane2);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CONDUCTNUMBER", "DISEASES", "DURATION"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jTabbedPane4.addTab("tab1", jScrollPane5);

        jTabbedPane1.addTab("nward3", jTabbedPane4);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CONDUCTNUMBER", "DISEASES", "DURATION"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jTabbedPane5.addTab("tab1", jScrollPane6);

        jTabbedPane1.addTab("eward1", jTabbedPane5);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CONDUCTNUMBER", "DISEASES", "DURATION"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        jTabbedPane6.addTab("tab1", jScrollPane7);

        jTabbedPane1.addTab("eward2", jTabbedPane6);

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CONDUCTNUMBER", "DISEASE", "DURATION"
            }
        ));
        jScrollPane8.setViewportView(jTable8);

        jTabbedPane7.addTab("tab1", jScrollPane8);
        jTabbedPane7.addTab("tab2", jTabbedPane22);

        jTabbedPane1.addTab("eward3", jTabbedPane7);

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CONDUCTNUMBER", "DISEASES", "DURATION"
            }
        ));
        jScrollPane9.setViewportView(jTable9);

        jTabbedPane8.addTab("tab1", jScrollPane9);

        jTabbedPane1.addTab("iward1", jTabbedPane8);

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CONDUCTNUMBER", "DISEASES", "DURATION"
            }
        ));
        jScrollPane10.setViewportView(jTable10);

        jTabbedPane9.addTab("tab1", jScrollPane10);

        jTable25.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NAME", "PROBLEM"
            }
        ));
        jScrollPane25.setViewportView(jTable25);

        jTabbedPane25.addTab("tab1", jScrollPane25);

        jTabbedPane9.addTab("gyno6", jTabbedPane25);

        jTabbedPane1.addTab("iward2", jTabbedPane9);

        jTable11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CONDUCTNUMBER", "DISEASES", "DURATION"
            }
        ));
        jScrollPane11.setViewportView(jTable11);

        jTabbedPane10.addTab("tab1", jScrollPane11);

        jTabbedPane1.addTab("iward3", jTabbedPane10);

        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CONDUCTNUMBER", "DISEASES", "DURATION"
            }
        ));
        jScrollPane13.setViewportView(jTable13);

        jTabbedPane3.addTab("tab1", jScrollPane13);

        jTable23.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane23.setViewportView(jTable23);

        jTabbedPane19.addTab("tab1", jScrollPane23);

        jTabbedPane3.addTab("tab2", jTabbedPane19);
        jTabbedPane3.addTab("tab3", jTabbedPane24);

        jTabbedPane1.addTab("lward2", jTabbedPane3);

        jTable14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CONDUCTNUMBER", "DISEASES", "DURATION"
            }
        ));
        jScrollPane14.setViewportView(jTable14);

        jTabbedPane12.addTab("tab1", jScrollPane14);

        jTabbedPane1.addTab("lward3", jTabbedPane12);

        jTable15.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "WarddNumber", "Available_Status", "Total_Seats"
            }
        ));
        jScrollPane15.setViewportView(jTable15);
        if (jTable15.getColumnModel().getColumnCount() > 0) {
            jTable15.getColumnModel().getColumn(2).setResizable(false);
        }

        jTabbedPane13.addTab("tab1", jScrollPane15);

        jTabbedPane1.addTab("wardstatus", jTabbedPane13);

        jTable17.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "AGE", "FATHERNAME", "ADDRESS", "WEIGHT", "CONDUCTNUMBER", "GENDER", "BLOODGROUP", "INJECTION", "DRUGHAPIT", "EATFOOD", "OPERATIONS", "COLD", "DISEASES"
            }
        ));
        jScrollPane17.setViewportView(jTable17);

        jTabbedPane15.addTab("tab1", jScrollPane17);

        jTabbedPane1.addTab("blooddonation", jTabbedPane15);

        jTable16.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "CLEAN", "SERVICE", "STAFF", "CARE", "DOCTOR", "EQUIPMENT", "FACILITY", "PROCESS", "HOSPITAL", "RECOMMENT"
            }
        ));
        jScrollPane16.setViewportView(jTable16);
        if (jTable16.getColumnModel().getColumnCount() > 0) {
            jTable16.getColumnModel().getColumn(10).setResizable(false);
        }

        jTabbedPane14.addTab("tab1", jScrollPane16);

        jTabbedPane1.addTab("feedback", jTabbedPane14);

        jTable21.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NAME", "PROBLEM"
            }
        ));
        jScrollPane21.setViewportView(jTable21);

        jTabbedPane18.addTab("tab1", jScrollPane21);

        jTabbedPane1.addTab("gyno1", jTabbedPane18);

        jTable22.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NAME", "PROBLEM"
            }
        ));
        jScrollPane22.setViewportView(jTable22);

        jTabbedPane20.addTab("gyno6", jScrollPane22);

        jTabbedPane1.addTab("gyno2", jTabbedPane20);

        jTable19.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DOCTOR", "AVAILABLE APPOINTMENT", "TOTALAPPOINTMENT"
            }
        ));
        jScrollPane19.setViewportView(jTable19);

        jTabbedPane21.addTab("tab1", jScrollPane19);

        jTabbedPane1.addTab("doctoravailable", jTabbedPane21);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NAME", "PROBLEM"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jTabbedPane16.addTab("tab1", jScrollPane4);

        jTabbedPane1.addTab("gyno3", jTabbedPane16);

        jTable18.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NAME", "PROBLEM"
            }
        ));
        jScrollPane18.setViewportView(jTable18);

        jTabbedPane17.addTab("tab1", jScrollPane18);

        jTabbedPane1.addTab("gyno4", jTabbedPane17);

        jTable24.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NAME", "PROBLEM"
            }
        ));
        jScrollPane24.setViewportView(jTable24);

        jTabbedPane23.addTab("tab1", jScrollPane24);

        jTabbedPane1.addTab("gyno5", jTabbedPane23);

        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAME", "CONDUCTNUMBER", "DISEASES", "DURATION"
            }
        ));
        jScrollPane12.setViewportView(jTable12);

        jTabbedPane11.addTab("tab1", jScrollPane12);

        jTabbedPane1.addTab("lward1", jTabbedPane11);

        jTable26.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NAME", "PROBLEM"
            }
        ));
        jScrollPane26.setViewportView(jTable26);

        jTabbedPane26.addTab("tab1", jScrollPane26);

        jTabbedPane1.addTab("gyno6", jTabbedPane26);

        jTable27.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NA,ME", "EMAIL", "PASSWORD"
            }
        ));
        jScrollPane27.setViewportView(jTable27);

        jTabbedPane27.addTab("tab1", jScrollPane27);

        jTabbedPane1.addTab("signin", jTabbedPane27);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1220, 1060));
        jTabbedPane1.setVisible(false);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "patientsdetails", "nward1", "nward2", "nward3", "eward1", "eward2", "eward3", "iward1", "iward2", "iward3", "lward1", "lward2", "lward3", "wardstatus", "feedback", "blood", "gyno1", "gyno2", "gyno3", "gyno4", "gyno5", "gyno6", "signin", "orthoward1", "orthoward2", "orthoward3", "orthoward4", "orthoward5", "orthoward6", "doctoravailable", " ", " ", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 120));

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel2.setBackground(new java.awt.Color(51, 255, 255));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 1280, 950));

        jLabel3.setBackground(new java.awt.Color(0, 102, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icu.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1650, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

 
             String stud = (String) jComboBox1.getSelectedItem();
       
        String name,dob,gender,cno,blo,add,dis,NAME,di,cn,du,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11,b12,b13,b14;
        
        
          try
          
        {
            Connection con = connection.getCon();
            Statement stmt = con.createStatement();
            
            if(stud=="patientsdetails")
            {
                DefaultTableModel t=(DefaultTableModel) jTable2.getModel();
        t.getDataVector().removeAllElements();
            jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(0);
            ResultSet q;
            q = stmt.executeQuery("select * from patients");
             while (q.next()) {
                name = q.getString("NAME");
                 dob = q.getString("PATIENTDOB");
                cno = q.getString("CONDUCTNUMBER");
                blo = q.getString("BLOODgroup");
                gender=q.getString("GENDER");
                add=q.getString("PATIENTADDRESS");
                dis=q.getString("PATIENTdisorder");
                
                String []rowdata={name,dob,cno,blo,gender,add,dis};
                t.addRow(rowdata);
            }}
            if(stud=="nward1"){
                DefaultTableModel t=(DefaultTableModel) jTable3.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(1);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from ward1");
             while (q1.next()) {
                NAME = q1.getString("NAME");
                 cn = q1.getString("CONDUCTNUM");
                di = q1.getString("DISEASE");
                du = q1.getString("DURATION");
                String []rowdata={NAME,cn,di,du};
                t.addRow(rowdata);
             }}
            if(stud=="nward2"){
                DefaultTableModel t=(DefaultTableModel) jTable3.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(2);
            ResultSet q2;
            q2 = stmt.executeQuery("select * from ward2");
             while (q2.next()) {
                NAME = q2.getString("NAME");
                 cn = q2.getString("CONDUCTNUM");
                di = q2.getString("DISEASE");
                du = q2.getString("DURATION");
                String []rowdata={NAME,cn,di,du};
                t.addRow(rowdata);
        }}if(stud=="nward3"){
                DefaultTableModel t=(DefaultTableModel) jTable5.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(3);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from ward3");
             while (q1.next()) {
                NAME = q1.getString("NAME");
                 cn = q1.getString("CONDUCTNUM");
                di = q1.getString("DISEASE");
                du = q1.getString("DURATION");
                String []rowdata={NAME,cn,di,du};
                t.addRow(rowdata);
             }}
        if(stud=="eward1"){
                DefaultTableModel t=(DefaultTableModel) jTable6.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(4);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from ward11");
             while (q1.next()) {
                NAME = q1.getString("NAME");
                 cn = q1.getString("CONDUCTNUM");
                di = q1.getString("DISEASE");
                du = q1.getString("DURATION");
                String []rowdata={NAME,cn,di,du};
                t.addRow(rowdata);
             }}
        if(stud=="eward2"){
                DefaultTableModel t=(DefaultTableModel) jTable7.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(5);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from ward12");
             while (q1.next()) {
                NAME = q1.getString("NAME");
                 cn = q1.getString("CONDUCTNUM");
                di = q1.getString("DISEASE");
                du = q1.getString("DURATION");
                String []rowdata={NAME,cn,di,du};
                t.addRow(rowdata);
             }}
        if(stud=="eward3"){
                DefaultTableModel t=(DefaultTableModel) jTable8.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(6);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from ward13");
             while (q1.next()) {
                NAME = q1.getString("NAME");
                 cn = q1.getString("CONDUCTNUM");
                di = q1.getString("DISEASE");
                du = q1.getString("DURATION");
                String []rowdata={NAME,cn,di,du};
                t.addRow(rowdata);
             }}
        if(stud=="iward1"){
                DefaultTableModel t=(DefaultTableModel) jTable9.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(7);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from ward16");
             while (q1.next()) {
                NAME = q1.getString("NAME");
                 cn = q1.getString("CONDUCTNUM");
                di = q1.getString("DISEASE");
                du = q1.getString("DURATION");
                String []rowdata={NAME,cn,di,du};
                t.addRow(rowdata);
             }}
        if(stud=="iward2"){
                DefaultTableModel t=(DefaultTableModel) jTable10.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(8);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from ward17");
             while (q1.next()) {
                NAME = q1.getString("NAME");
                 cn = q1.getString("CONDUCTNUM");
                di = q1.getString("DISEASE");
                du = q1.getString("DURATION");
                String []rowdata={NAME,cn,di,du};
                t.addRow(rowdata);
             }}
        if(stud=="iward3"){
                DefaultTableModel t=(DefaultTableModel) jTable11.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(9);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from ward18");
             while (q1.next()) {
                NAME = q1.getString("NAME");
                 cn = q1.getString("CONDUCTNUM");
                di = q1.getString("DISEASE");
                du = q1.getString("DURATION");
                String []rowdata={NAME,cn,di,du};
                t.addRow(rowdata);
             }}
        if(stud=="lward1"){
                DefaultTableModel t=(DefaultTableModel) jTable12.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(10);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from ward19");
             while (q1.next()) {
                NAME = q1.getString("NAME");
                 cn = q1.getString("CONDUCTNUM");
                di = q1.getString("DISEASE");
                du = q1.getString("DURATION");
                String []rowdata={NAME,cn,di,du};
                t.addRow(rowdata);
             }}
        if(stud=="lward2"){
                DefaultTableModel t=(DefaultTableModel) jTable13.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(11);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from ward20");
             while (q1.next()) {
                NAME = q1.getString("NAME");
                 cn = q1.getString("CONDUCTNUM");
                di = q1.getString("DISEASE");
                du = q1.getString("DURATION");
                String []rowdata={NAME,cn,di,du};
                t.addRow(rowdata);
             }}
        if(stud=="lward3"){
                DefaultTableModel t=(DefaultTableModel) jTable14.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(12);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from ward21");
             while (q1.next()) {
                NAME = q1.getString("NAME");
                 cn = q1.getString("CONDUCTNUM");
                di = q1.getString("DISEASE");
                du = q1.getString("DURATION");
                String []rowdata={NAME,cn,di,du};
                t.addRow(rowdata);
             }}
        if(stud=="wardstatus"){
                DefaultTableModel t=(DefaultTableModel) jTable15.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(13);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from warddetails");
             while (q1.next()) {
                NAME = q1.getString("ward_no");
                 cn = q1.getString("available_seats");
                di = q1.getString("total_seats");
              
                String []rowdata={NAME,cn,di};
                t.addRow(rowdata);
             }}
        if(stud=="feedback"){
                DefaultTableModel t=(DefaultTableModel) jTable16.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(14);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from feedback");
             while (q1.next()) {
                NAME = q1.getString("name");
                f1  = q1.getString("feed1");
                f2 = q1.getString("feed2");
              f3  = q1.getString("feed3");
                f4 = q1.getString("feed4");
                f5  = q1.getString("feed5");
                f6 = q1.getString("feed6");
                f7  = q1.getString("feed7");
                f8 = q1.getString("feed8");
                f9  = q1.getString("feed9");
                f10 = q1.getString("feed10");
                String []rowdata={NAME,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10};
                t.addRow(rowdata);
             }}
        
        if(stud=="blood")
            {
                DefaultTableModel t=(DefaultTableModel) jTable17.getModel();
        t.getDataVector().removeAllElements();
            jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(15);
            ResultSet q;
            q = stmt.executeQuery("select * from blood2");
             while (q.next()) {
               b1  = q.getString("NAME");
                b2 = q.getString("AGE");
                b3 = q.getString("FATHERNAME");
                b4 = q.getString("ADDRESS");
               b5 =q.getString("WEIGHT");
               b6 =q.getString("CONDUCTNUMBER");
               b7 =q.getString("GENDER");
               b8  = q.getString("BLOODGROUP");
               b9  = q.getString("INJECTION");
               b10  = q.getString("DRUGHABIT");
               b11  = q.getString("EAT_FOOD_MORNING");
               b12 =q.getString("OPERATIONS");
              b13  =q.getString("COLD_or_FEVER");
              b14  =q.getString("DISEASE");
                String []rowdata={b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11,b12,b13,b14};
                t.addRow(rowdata);
            }}
        if(stud=="gyno1"){
                DefaultTableModel t=(DefaultTableModel) jTable18.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(16);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from g1");
             while (q1.next()) {
                b1 = q1.getString("name");
           
                di = q1.getString("problem");
              
                String []rowdata={b1,di};
                t.addRow(rowdata);
             }}
          if(stud=="gyno2"){
                DefaultTableModel t=(DefaultTableModel) jTable4.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(17);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from g2");
             while (q1.next()) {
                b1 = q1.getString("name");
           
                di = q1.getString("problem");
              
                String []rowdata={b1,di};
                t.addRow(rowdata);
             }}
            if(stud=="gyno3"){
                DefaultTableModel t=(DefaultTableModel) jTable4.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(19);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from g2");
             while (q1.next()) {
                b1 = q1.getString("name");
           
                di = q1.getString("problem");
              
                String []rowdata={b1,di};
                t.addRow(rowdata);
             }}
              if(stud=="gyno4"){
                DefaultTableModel t=(DefaultTableModel) jTable18.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(20);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from g2");
             while (q1.next()) {
                b1 = q1.getString("name");
           
                di = q1.getString("problem");
              
                String []rowdata={b1,di};
                t.addRow(rowdata);
             }}
                if(stud=="gyno5"){
                DefaultTableModel t=(DefaultTableModel) jTable24.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(21);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from g2");
             while (q1.next()) {
                b1 = q1.getString("name");
           
                di = q1.getString("problem");
              
                String []rowdata={b1,di};
                t.addRow(rowdata);
             }}
                  if(stud=="gyno6"){
                DefaultTableModel t=(DefaultTableModel) jTable26.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(23);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from g2");
             while (q1.next()) {
                b1 = q1.getString("name");
           
                di = q1.getString("problem");
              
                String []rowdata={b1,di};
                t.addRow(rowdata);
             }}
        if(stud=="doctoravailable"){
                DefaultTableModel t=(DefaultTableModel) jTable19.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(18);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from doctordetails");
             while (q1.next()) {
                b1 = q1.getString("special");
           
                di = q1.getString("available_appointment");
               b2 = q1.getString("total_appointment");
                String []rowdata={b1,di,b2};
                t.addRow(rowdata);
             }}
        
        if(stud=="signin"){
                DefaultTableModel t=(DefaultTableModel) jTable27.getModel();
        t.getDataVector().removeAllElements();
                jTabbedPane1.setVisible(true);
            jTabbedPane1.setSelectedIndex(24);
            ResultSet q1;
            q1 = stmt.executeQuery("select * from user");
             while (q1.next()) {
                b1 = q1.getString("Name");
           
                di = q1.getString("Email");
               b2 = q1.getString("Password");
                String []rowdata={b1,di,b2};
                t.addRow(rowdata);
             }}
        }
                 catch(Exception f)
            { 
            System.out.println(f);
                         }
           
       
        
        
        
           // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false);
new Hospital1().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(displaydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(displaydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(displaydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(displaydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                   displaydetails s = new displaydetails();
                s.setVisible(true);
                s.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane11;
    private javax.swing.JTabbedPane jTabbedPane12;
    private javax.swing.JTabbedPane jTabbedPane13;
    private javax.swing.JTabbedPane jTabbedPane14;
    private javax.swing.JTabbedPane jTabbedPane15;
    private javax.swing.JTabbedPane jTabbedPane16;
    private javax.swing.JTabbedPane jTabbedPane17;
    private javax.swing.JTabbedPane jTabbedPane18;
    private javax.swing.JTabbedPane jTabbedPane19;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane20;
    private javax.swing.JTabbedPane jTabbedPane21;
    private javax.swing.JTabbedPane jTabbedPane22;
    private javax.swing.JTabbedPane jTabbedPane23;
    private javax.swing.JTabbedPane jTabbedPane24;
    private javax.swing.JTabbedPane jTabbedPane25;
    private javax.swing.JTabbedPane jTabbedPane26;
    private javax.swing.JTabbedPane jTabbedPane27;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JTabbedPane jTabbedPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable11;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable13;
    private javax.swing.JTable jTable14;
    private javax.swing.JTable jTable15;
    private javax.swing.JTable jTable16;
    private javax.swing.JTable jTable17;
    private javax.swing.JTable jTable18;
    private javax.swing.JTable jTable19;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable20;
    private javax.swing.JTable jTable21;
    private javax.swing.JTable jTable22;
    private javax.swing.JTable jTable23;
    private javax.swing.JTable jTable24;
    private javax.swing.JTable jTable25;
    private javax.swing.JTable jTable26;
    private javax.swing.JTable jTable27;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    // End of variables declaration//GEN-END:variables
}
