
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sedhu
 */
public class Food extends javax.swing.JFrame {

    /**
     * Creates new form Food
     */
    public Food() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jComboBox13 = new javax.swing.JComboBox<>();
        jComboBox14 = new javax.swing.JComboBox<>();
        jComboBox15 = new javax.swing.JComboBox<>();
        jComboBox16 = new javax.swing.JComboBox<>();
        jComboBox17 = new javax.swing.JComboBox<>();
        jComboBox18 = new javax.swing.JComboBox<>();
        jComboBox19 = new javax.swing.JComboBox<>();
        jComboBox20 = new javax.swing.JComboBox<>();
        jComboBox21 = new javax.swing.JComboBox<>();
        jComboBox22 = new javax.swing.JComboBox<>();
        jComboBox23 = new javax.swing.JComboBox<>();
        jComboBox24 = new javax.swing.JComboBox<>();
        jComboBox25 = new javax.swing.JComboBox<>();
        jComboBox26 = new javax.swing.JComboBox<>();
        jComboBox27 = new javax.swing.JComboBox<>();
        jComboBox28 = new javax.swing.JComboBox<>();
        jComboBox29 = new javax.swing.JComboBox<>();
        jComboBox30 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel1.setText("FOOD COUNTER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 460, 64));

        jCheckBox1.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox1.setText("MUSHROOM BRIYANI@100");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("RICE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 90, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel3.setText("SNACKS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, 38));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel4.setText("DRINKS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, -1, -1));

        jCheckBox2.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox2.setText("TOMATO RICE@50");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 210, -1));

        jCheckBox3.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox3.setText("CURD RICE@25");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 210, -1));

        jCheckBox4.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox4.setText("MUTTON BRIYANI@150");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 210, -1));

        jCheckBox5.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox5.setText("VEG BRIYANI@120");
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 210, -1));

        jCheckBox6.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox6.setText("SAMBAR RICE@60");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 210, -1));

        jCheckBox7.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox7.setText("CHICKEN BRIYANI@130");
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 210, -1));

        jCheckBox8.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox8.setText("MINT RICE@50");
        jPanel1.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 210, -1));

        jCheckBox9.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox9.setText("LEMON RICE@50");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 210, -1));

        jCheckBox10.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox10.setText("TAMRIND RICE@50");
        jPanel1.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 210, -1));

        jCheckBox11.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox11.setText("VEG PUFFS@15");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 160, -1));

        jCheckBox12.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox12.setText("BONDA@8");
        jPanel1.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 160, -1));

        jCheckBox13.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox13.setText("VADAI@8");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 162, -1));

        jCheckBox14.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox14.setText("EGG PUFFS@20");
        jPanel1.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 160, -1));

        jCheckBox15.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox15.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox15.setText("CHICKEN PUFFS@25");
        jPanel1.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 160, -1));

        jCheckBox16.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox16.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox16.setText("VEG ROLL@15");
        jPanel1.add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 158, -1));

        jCheckBox17.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox17.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox17.setText("COOKIE@30");
        jPanel1.add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 160, -1));

        jCheckBox18.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox18.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox18.setText("ROLL CAKE@10");
        jPanel1.add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 160, -1));

        jCheckBox19.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox19.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox19.setText("DATES@80");
        jPanel1.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 160, -1));

        jCheckBox20.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox20.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox20.setText("BISCUIT@20");
        jPanel1.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 160, -1));

        jCheckBox21.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox21.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox21.setText("TEA@12");
        jPanel1.add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 160, -1));

        jCheckBox22.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox22.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox22.setText("COFFEE@15");
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 160, -1));

        jCheckBox23.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox23.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox23.setText("MILK SHAKE@35 ");
        jPanel1.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 160, -1));

        jCheckBox24.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox24.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox24.setText("LEMON JUICE@20");
        jPanel1.add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 160, -1));

        jCheckBox25.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox25.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox25.setText("POMOGRANITE JUICE@50");
        jPanel1.add(jCheckBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 210, -1));

        jCheckBox26.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox26.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox26.setText("ORANGE JUICE@30");
        jPanel1.add(jCheckBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 161, -1));

        jCheckBox27.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox27.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox27.setText("ROSE MILK@15");
        jPanel1.add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 160, -1));

        jCheckBox28.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox28.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox28.setText("FROOTI@20");
        jPanel1.add(jCheckBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 161, -1));

        jCheckBox29.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox29.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox29.setText("CONE ICE@35");
        jPanel1.add(jCheckBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 160, -1));

        jCheckBox30.setBackground(new java.awt.Color(0, 204, 204));
        jCheckBox30.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jCheckBox30.setText("CHACOBAR @20");
        jCheckBox30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox30ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 160, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton1.setText("ORDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 650, -1, 30));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 60, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", " ", " " }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jComboBox3.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jComboBox4.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jComboBox5.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        jComboBox6.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        jComboBox7.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        jComboBox8.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jComboBox9.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        jComboBox10.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));

        jComboBox11.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox11.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        jComboBox12.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox12.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        jComboBox13.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        jComboBox14.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox14.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jComboBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox14ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        jComboBox15.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox15.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        jComboBox16.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox16.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));

        jComboBox17.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox17.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        jComboBox18.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox18.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        jComboBox19.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox19.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, -1, -1));

        jComboBox20.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox20.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, -1, -1));

        jComboBox21.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox21.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, -1, -1));

        jComboBox22.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox22.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 220, -1, -1));

        jComboBox23.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox23.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox23.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 250, -1, -1));

        jComboBox24.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox24.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox24.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 280, -1, -1));

        jComboBox25.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox25.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox25.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 310, -1, -1));

        jComboBox26.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox26.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox26.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 340, -1, -1));

        jComboBox27.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox27.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox27.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 370, -1, -1));

        jComboBox28.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox28.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox28.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 400, -1, 30));

        jComboBox29.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox29.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox29.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 430, -1, -1));

        jComboBox30.setBackground(new java.awt.Color(255, 102, 102));
        jComboBox30.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jComboBox30.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("NAME:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 549, 70, 20));

        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 550, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 117, 1707, 757));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        new Hospital1().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int amount=0;
        if(jCheckBox1.isSelected())
        {
            if(jComboBox1.getSelectedItem()=="1"){
            amount+=100;
            }
            if(jComboBox1.getSelectedItem()=="2"){
            amount+=100*2;
        }
            if(jComboBox1.getSelectedItem()=="3"){
            amount+=100*3;
        }
                   // JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
            
        if(jCheckBox2.isSelected())
        {
            if(jComboBox2.getSelectedItem()=="1"){
            amount+=50;
            }
            if(jComboBox2.getSelectedItem()=="2"){
            amount+=50*2;
        }
            if(jComboBox2.getSelectedItem()=="3"){
            amount+=50*3;
        }
                  //  JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox3.isSelected()){
             if(jComboBox3.getSelectedItem()=="1"){
            amount+=25;
            }
            if(jComboBox3.getSelectedItem()=="2"){
            amount+=25*2;
        }
            if(jComboBox3.getSelectedItem()=="3"){
            amount+=25*3;
        }
                    //JOptionPane.showMessageDialog(null,"CURD RICE:"+amount);

        }
        if(jCheckBox4.isSelected())
        {
               if(jComboBox4.getSelectedItem()=="1"){
            amount+=150;
            }
            if(jComboBox4.getSelectedItem()=="2"){
            amount+=150*2;
        }
            if(jComboBox4.getSelectedItem()=="3"){
            amount+=150*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox5.isSelected())
        {
               if(jComboBox5.getSelectedItem()=="1"){
            amount+=120;
            }
            if(jComboBox5.getSelectedItem()=="2"){
            amount+=120*2;
        }
            if(jComboBox5.getSelectedItem()=="3"){
            amount+=120*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox6.isSelected())
        {
               if(jComboBox2.getSelectedItem()=="1"){
            amount+=60;
            }
            if(jComboBox2.getSelectedItem()=="2"){
            amount+=60*2;
        }
            if(jComboBox2.getSelectedItem()=="3"){
            amount+=60*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox7.isSelected())
        {
              if(jComboBox7.getSelectedItem()=="1"){
            amount+=130;
            }
            if(jComboBox7.getSelectedItem()=="2"){
            amount+=130*2;
        }
            if(jComboBox7.getSelectedItem()=="3"){
            amount+=130*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox8.isSelected())
        {
               if(jComboBox8.getSelectedItem()=="1"){
            amount+=50;
            }
            if(jComboBox8.getSelectedItem()=="2"){
            amount+=50*2;
        }
            if(jComboBox8.getSelectedItem()=="3"){
            amount+=50*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox9.isSelected())
        {
               if(jComboBox9.getSelectedItem()=="1"){
            amount+=50;
            }
            if(jComboBox9.getSelectedItem()=="2"){
            amount+=50*2;
        }
            if(jComboBox9.getSelectedItem()=="3"){
            amount+=50*3;
        }
//                    JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox10.isSelected())
        {
               if(jComboBox10.getSelectedItem()=="1"){
            amount+=50;
            }
            if(jComboBox10.getSelectedItem()=="2"){
            amount+=50*2;
        }
            if(jComboBox10.getSelectedItem()=="3"){
            amount+=50*3;
        }
//                    JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox11.isSelected())
        {
               if(jComboBox11.getSelectedItem()=="1"){
            amount+=15;
            }
            if(jComboBox11.getSelectedItem()=="2"){
            amount+=15*2;
        }
            if(jComboBox11.getSelectedItem()=="3"){
            amount+=15*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox12.isSelected())
        {
               if(jComboBox12.getSelectedItem()=="1"){
            amount+=8;
            }
            if(jComboBox12.getSelectedItem()=="2"){
            amount+=8*2;
        }
            if(jComboBox12.getSelectedItem()=="3"){
            amount+=8*3;
        }
//                    JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox13.isSelected()){
               if(jComboBox13.getSelectedItem()=="1"){
            amount+=8;
            }
            if(jComboBox13.getSelectedItem()=="2"){
            amount+=8*2;
        }
            if(jComboBox13.getSelectedItem()=="3"){
            amount+=8*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox14.isSelected())
        {
               if(jComboBox14.getSelectedItem()=="1"){
            amount+=20;
            }
            if(jComboBox14.getSelectedItem()=="2"){
            amount+=20*2;
        }
            if(jComboBox14.getSelectedItem()=="3"){
            amount+=20*3;
        }
//                    JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox15.isSelected())
        {
               if(jComboBox15.getSelectedItem()=="1"){
            amount+=25;
            }
            if(jComboBox15.getSelectedItem()=="2"){
            amount+=25*2;
        }
            if(jComboBox15.getSelectedItem()=="3"){
            amount+=25*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox16.isSelected())
        {
             if(jComboBox16.getSelectedItem()=="1"){
            amount+=15;
            }
            if(jComboBox16.getSelectedItem()=="2"){
            amount+=15*2;
        }
            if(jComboBox16.getSelectedItem()=="3"){
            amount+=15*3;
        }
//                    JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox17.isSelected())
        {
              if(jComboBox17.getSelectedItem()=="1"){
            amount+=30;
            }
            if(jComboBox17.getSelectedItem()=="2"){
            amount+=30*2;
        }
            if(jComboBox17.getSelectedItem()=="3"){
            amount+=30*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox18.isSelected())
        {
               if(jComboBox18.getSelectedItem()=="1"){
            amount+=10;
            }
            if(jComboBox18.getSelectedItem()=="2"){
            amount+=10*2;
        }
            if(jComboBox18.getSelectedItem()=="3"){
            amount+=10*3;
        }
//                    JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox19.isSelected())
        {
               if(jComboBox19.getSelectedItem()=="1"){
            amount+=80;
            }
            if(jComboBox19.getSelectedItem()=="2"){
            amount+=80*2;
        }
            if(jComboBox19.getSelectedItem()=="3"){
            amount+=80*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox20.isSelected())
        {
               if(jComboBox2.getSelectedItem()=="1"){
            amount+=20;
            }
            if(jComboBox2.getSelectedItem()=="2"){
            amount+=20*2;
        }
            if(jComboBox2.getSelectedItem()=="3"){
            amount+=20*3;
        }
                  //  JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox21.isSelected())
        {
               if(jComboBox21.getSelectedItem()=="1"){
            amount+=12;
            }
            if(jComboBox21.getSelectedItem()=="2"){
            amount+=12*2;
        }
            if(jComboBox21.getSelectedItem()=="3"){
            amount+=12*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox22.isSelected())
        {
               if(jComboBox22.getSelectedItem()=="1"){
            amount+=15;
            }
            if(jComboBox22.getSelectedItem()=="2"){
            amount+=15*2;
        }
            if(jComboBox22.getSelectedItem()=="3"){
            amount+=15*3;
        }
//                    JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox23.isSelected())
        {
               if(jComboBox23.getSelectedItem()=="1"){
            amount+=35;
            }
            if(jComboBox23.getSelectedItem()=="2"){
            amount+=35*2;
        }
            if(jComboBox23.getSelectedItem()=="3"){
            amount+=35*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox24.isSelected()){
               if(jComboBox24.getSelectedItem()=="1"){
            amount+=20;
            }
            if(jComboBox24.getSelectedItem()=="2"){
            amount+=20*2;
        }
            if(jComboBox24.getSelectedItem()=="3"){
            amount+=20*3;
        }
//                    JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox25.isSelected())
        {
              if(jComboBox25.getSelectedItem()=="1"){
            amount+=50;
            }
            if(jComboBox25.getSelectedItem()=="2"){
            amount+=50*2;
        }
            if(jComboBox25.getSelectedItem()=="3"){
            amount+=50*3;
        }
                  //  JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox26.isSelected())
        {
               if(jComboBox26.getSelectedItem()=="1"){
            amount+=30;
            }
            if(jComboBox26.getSelectedItem()=="2"){
            amount+=30*2;
        }
            if(jComboBox26.getSelectedItem()=="3"){
            amount+=30*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox27.isSelected())
        {
               if(jComboBox2.getSelectedItem()=="1"){
            amount+=15;
            }
            if(jComboBox2.getSelectedItem()=="2"){
            amount+=15*2;
        }
            if(jComboBox2.getSelectedItem()=="3"){
            amount+=15*3;
        }
//                    JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox28.isSelected())
        {
              if(jComboBox28.getSelectedItem()=="1"){
            amount+=20;
            }
            if(jComboBox28.getSelectedItem()=="2"){
            amount+=20*2;
        }
            if(jComboBox28.getSelectedItem()=="3"){
            amount+=20*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox29.isSelected())
        {
              if(jComboBox29.getSelectedItem()=="1"){
            amount+=35;
            }
            if(jComboBox29.getSelectedItem()=="2"){
            amount+=35*2;
        }
            if(jComboBox2.getSelectedItem()=="3"){
            amount+=35*3;
        }
                    //JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
        if(jCheckBox30.isSelected())
        {
              if(jComboBox30.getSelectedItem()=="1"){
            amount+=20;
            }
            if(jComboBox30.getSelectedItem()=="2"){
            amount+=20*2;
        }
            if(jComboBox30.getSelectedItem()=="3"){
            amount+=20*3;
        }
//                    JOptionPane.showMessageDialog(null,"MUSHROOM BRIYANI:"+amount);

        }
      String s1=jTextField1.getText();
        javax.swing.JOptionPane.showMessageDialog(null,"\nTOTAL AMOUNT:"+amount +"\nPURCHASED BY:"+s1);// TODO add your handling code here:;

        //JOptionPane.showMessageDialog(null,"TOTAL:"+amount\n + "order by"+jTextField1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox30ActionPerformed

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox22ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 Food s = new Food();
                s.setVisible(true);
                s.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JComboBox<String> jComboBox21;
    private javax.swing.JComboBox<String> jComboBox22;
    private javax.swing.JComboBox<String> jComboBox23;
    private javax.swing.JComboBox<String> jComboBox24;
    private javax.swing.JComboBox<String> jComboBox25;
    private javax.swing.JComboBox<String> jComboBox26;
    private javax.swing.JComboBox<String> jComboBox27;
    private javax.swing.JComboBox<String> jComboBox28;
    private javax.swing.JComboBox<String> jComboBox29;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox30;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
