/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sedhu
 */
public class pharm extends javax.swing.JFrame {

    /**
     * Creates new form pharm
     */
    public pharm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox2 = new javax.swing.JCheckBox();
        jComboBox2 = new javax.swing.JComboBox<>();
        jCheckBox3 = new javax.swing.JCheckBox();
        jComboBox3 = new javax.swing.JComboBox<>();
        jCheckBox4 = new javax.swing.JCheckBox();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jComboBox6 = new javax.swing.JComboBox<>();
        jCheckBox7 = new javax.swing.JCheckBox();
        jComboBox7 = new javax.swing.JComboBox<>();
        jCheckBox8 = new javax.swing.JCheckBox();
        jComboBox8 = new javax.swing.JComboBox<>();
        jCheckBox9 = new javax.swing.JCheckBox();
        jComboBox9 = new javax.swing.JComboBox<>();
        jCheckBox10 = new javax.swing.JCheckBox();
        jComboBox10 = new javax.swing.JComboBox<>();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jComboBox13 = new javax.swing.JComboBox<>();
        jComboBox14 = new javax.swing.JComboBox<>();
        jComboBox15 = new javax.swing.JComboBox<>();
        jComboBox16 = new javax.swing.JComboBox<>();
        jComboBox17 = new javax.swing.JComboBox<>();
        jComboBox18 = new javax.swing.JComboBox<>();
        jComboBox19 = new javax.swing.JComboBox<>();
        jComboBox20 = new javax.swing.JComboBox<>();
        jComboBox21 = new javax.swing.JComboBox<>();
        jComboBox22 = new javax.swing.JComboBox<>();
        jComboBox23 = new javax.swing.JComboBox<>();
        jComboBox24 = new javax.swing.JComboBox<>();
        jComboBox25 = new javax.swing.JComboBox<>();
        jComboBox26 = new javax.swing.JComboBox<>();
        jComboBox27 = new javax.swing.JComboBox<>();
        jComboBox28 = new javax.swing.JComboBox<>();
        jComboBox29 = new javax.swing.JComboBox<>();
        jComboBox30 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel1.setText("PHARMACY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 41, 322, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel12.setText("NAME:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 157, 75, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 161, 173, -1));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox1.setText("ACETAMINOPHEN@200");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 228, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", " " }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 234, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox2.setText("BUPROFEIN@80");
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 276, 187, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 282, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox3.setText("ASPIRIN@60");
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 324, 153, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        jCheckBox4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox4.setText("CETRIZINE@90");
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 372, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 378, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 426, -1, -1));

        jCheckBox5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox5.setText("LORATADINE@300");
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 420, -1, -1));

        jCheckBox6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox6.setText("RANTIDINE@250");
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 462, 196, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 468, -1, -1));

        jCheckBox7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox7.setText("OMEPRAZOLE@200");
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 504, 220, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, -1, -1));

        jCheckBox8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox8.setText("PANTOPRAZOLE@200");
        jCheckBox8.setToolTipText("");
        jPanel1.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 563, 251, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 569, -1, -1));

        jCheckBox9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox9.setText("METFORMIN@190");
        jPanel1.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 605, 216, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 611, -1, -1));

        jCheckBox10.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox10.setText("LEVOTHYROXINE@100");
        jPanel1.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 647, -1, -1));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 653, -1, -1));

        jCheckBox11.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox11.setText("ATORVASTATAIN@120");
        jPanel1.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 228, 257, -1));

        jCheckBox12.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox12.setText("SIMVASTATIN@40");
        jPanel1.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 276, 214, -1));

        jCheckBox13.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox13.setText("LISINOPRIL@200");
        jPanel1.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 324, 200, -1));

        jCheckBox14.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox14.setText("AMOLOCIPINDE@300");
        jPanel1.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 372, -1, -1));

        jCheckBox15.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox15.setText("LOSARTAN@330");
        jPanel1.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 420, 208, -1));

        jCheckBox16.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox16.setText("METROPROCOL@240");
        jPanel1.add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 462, 229, -1));

        jCheckBox17.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox17.setText("ALBUTEROL@250");
        jPanel1.add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 504, 198, -1));

        jCheckBox18.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox18.setText("FLUTICASONE@100");
        jPanel1.add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 563, -1, -1));

        jCheckBox19.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox19.setText("SERTRALINE@250");
        jPanel1.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 605, 207, -1));

        jCheckBox20.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox20.setText("ESCITALOPRAM@220");
        jPanel1.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 647, 229, -1));

        jCheckBox21.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox21.setText("LEXAPRO@170");
        jPanel1.add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 228, -1, -1));

        jCheckBox22.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox22.setText("CYMBALTA@140");
        jPanel1.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 276, -1, -1));

        jCheckBox23.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox23.setText("NEUROTONIN@120");
        jPanel1.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 324, -1, -1));

        jCheckBox24.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox24.setText("LYRICA@180");
        jPanel1.add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 372, -1, -1));

        jCheckBox25.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox25.setText("COUMADIN@280");
        jPanel1.add(jCheckBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 420, 209, -1));

        jCheckBox26.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox26.setText("PLADIX@140");
        jPanel1.add(jCheckBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 462, 162, -1));

        jCheckBox27.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox27.setText("INSULIN@500");
        jPanel1.add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 504, 175, -1));

        jCheckBox28.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox28.setText("HYDR0THIADE@200");
        jPanel1.add(jCheckBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 563, -1, -1));

        jCheckBox29.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox29.setText("LASIX@70");
        jPanel1.add(jCheckBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 605, 135, -1));

        jCheckBox30.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jCheckBox30.setText("SYMICORT@410");
        jPanel1.add(jCheckBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1194, 647, 191, -1));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 234, -1, -1));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 284, -1, -1));

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 330, -1, -1));

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 378, -1, -1));

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 426, -1, -1));

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 470, -1, -1));

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1038, 510, -1, -1));

        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 569, -1, -1));

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 611, -1, -1));

        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 653, -1, -1));

        jComboBox21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1448, 234, -1, -1));

        jComboBox22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1448, 282, -1, -1));

        jComboBox23.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1448, 330, -1, -1));

        jComboBox24.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1448, 378, -1, -1));

        jComboBox25.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1448, 420, -1, -1));

        jComboBox26.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1448, 468, -1, -1));

        jComboBox27.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1448, 510, -1, -1));

        jComboBox28.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1448, 569, -1, -1));

        jComboBox29.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1448, 611, -1, -1));

        jComboBox30.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel1.add(jComboBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1448, 653, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setText("ORDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 761, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1436, 92, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 int amount=0;
        if(jCheckBox1.isSelected())
        { if(jComboBox1.getSelectedItem()=="1"){
            amount+=200*1;}
         if(jComboBox1.getSelectedItem()=="2"){
            amount+=200*2;}
          if(jComboBox1.getSelectedItem()=="3"){
            amount+=200*3;}
        }
        if(jCheckBox2.isSelected())
        {
            if(jComboBox2.getSelectedItem()=="1"){
            amount+=80*1;}
         if(jComboBox2.getSelectedItem()=="2"){
            amount+=80*2;}
          if(jComboBox2.getSelectedItem()=="3"){
            amount+=80*3;}
        }
        if(jCheckBox3.isSelected()){
            if(jComboBox3.getSelectedItem()=="1"){
            amount+=60*1;}
         if(jComboBox3.getSelectedItem()=="2"){
            amount+=60*2;}
          if(jComboBox3.getSelectedItem()=="3"){
            amount+=60*3;}
        }
        if(jCheckBox4.isSelected())
        {
            if(jComboBox4.getSelectedItem()=="1"){
            amount+=90*1;}
         if(jComboBox4.getSelectedItem()=="2"){
            amount+=90*2;}
          if(jComboBox4.getSelectedItem()=="3"){
            amount+=90*3;}
        }
        if(jCheckBox5.isSelected())
        {
            if(jComboBox5.getSelectedItem()=="1"){
            amount+=300*1;}
         if(jComboBox5.getSelectedItem()=="2"){
            amount+=300*2;}
          if(jComboBox5.getSelectedItem()=="3"){
            amount+=300*3;}
        }
        if(jCheckBox6.isSelected())
        {
            if(jComboBox6.getSelectedItem()=="1"){
            amount+=250*1;}
         if(jComboBox6.getSelectedItem()=="2"){
            amount+=250*2;}
          if(jComboBox6.getSelectedItem()=="3"){
            amount+=250*3;}
        }
        if(jCheckBox7.isSelected())
        {
            if(jComboBox7.getSelectedItem()=="1"){
            amount+=200*1;}
         if(jComboBox7.getSelectedItem()=="2"){
            amount+=200*2;}
          if(jComboBox7.getSelectedItem()=="3"){
            ;amount+=200*3;}
        }
        if(jCheckBox8.isSelected())
        {
           if(jComboBox8.getSelectedItem()=="1"){
            amount+=200*1;}
         if(jComboBox8.getSelectedItem()=="2"){
            amount+=200*2;}
          if(jComboBox8.getSelectedItem()=="3"){
            amount+=200*3;}
        }

        if(jCheckBox9.isSelected())
        {
           if(jComboBox9.getSelectedItem()=="1"){
            amount+=190*1;}
         if(jComboBox9.getSelectedItem()=="2"){
            amount+=190*2;}
          if(jComboBox9.getSelectedItem()=="3"){
            amount+=190*3;}
        }
        if(jCheckBox10.isSelected())
        {
            if(jComboBox10.getSelectedItem()=="1"){
            amount+=100*1;}
         if(jComboBox10.getSelectedItem()=="2"){
            amount+=100*2;}
          if(jComboBox10.getSelectedItem()=="3"){
            amount+=100*3;}
        }
        if(jCheckBox11.isSelected()){
            if(jComboBox11.getSelectedItem()=="1"){
            amount+=120*1;}
         if(jComboBox11.getSelectedItem()=="2"){
            amount+=120*2;}
          if(jComboBox11.getSelectedItem()=="3"){
            amount+=120*3;}
        }
        if(jCheckBox12.isSelected())
        {
            if(jComboBox12.getSelectedItem()=="1"){
            amount+=40*1;}
         if(jComboBox12.getSelectedItem()=="2"){
            amount+=40*2;}
          if(jComboBox12.getSelectedItem()=="3"){
            amount+=40*3;}
        }
        if(jCheckBox13.isSelected())
        {
            if(jComboBox13.getSelectedItem()=="1"){
            amount+=200*1;}
         if(jComboBox13.getSelectedItem()=="2"){
            amount+=200*2;}
          if(jComboBox13.getSelectedItem()=="3"){
            amount+=200*3;}
        }
        if(jCheckBox14.isSelected())
        {
            if(jComboBox14.getSelectedItem()=="1"){
            amount+=300*1;}
         if(jComboBox14.getSelectedItem()=="2"){
            amount+=300*2;}
          if(jComboBox14.getSelectedItem()=="3"){
            amount+=300*3;}
        }
           
        if(jCheckBox15.isSelected())
        {
            if(jComboBox15.getSelectedItem()=="1"){
            amount+=330*1;}
         if(jComboBox15.getSelectedItem()=="2"){
            amount+=330*2;}
          if(jComboBox15.getSelectedItem()=="3"){
            amount+=330*3;}
        }
        if(jCheckBox16.isSelected())
        {
           if(jComboBox16.getSelectedItem()=="1"){
            amount+=240*1;}
         if(jComboBox16.getSelectedItem()=="2"){
            amount+=240*2;}
          if(jComboBox16.getSelectedItem()=="3"){
            amount+=240*3;}
        }
        if(jCheckBox17.isSelected())
        {
            if(jComboBox17.getSelectedItem()=="1"){
            amount+=250*1;}
         if(jComboBox17.getSelectedItem()=="2"){
            amount+=250*2;}
          if(jComboBox17.getSelectedItem()=="3"){
            amount+=250*3;}
        }
        if(jCheckBox18.isSelected())
        {
           if(jComboBox18.getSelectedItem()=="1"){
            amount+=100*1;}
         if(jComboBox18.getSelectedItem()=="2"){
            amount+=100*2;}
          if(jComboBox18.getSelectedItem()=="3"){
            amount+=100*3;}
        }
        if(jCheckBox19.isSelected()){
            if(jComboBox19.getSelectedItem()=="1"){
            amount+=250*1;}
         if(jComboBox19.getSelectedItem()=="2"){
            amount+=250*2;}
          if(jComboBox19.getSelectedItem()=="3"){
            amount+=250*3;}
        }
        if(jCheckBox20.isSelected())
        {
           if(jComboBox20.getSelectedItem()=="1"){
            amount+=220*1;}
         if(jComboBox20.getSelectedItem()=="2"){
            amount+=220*2;}
          if(jComboBox20.getSelectedItem()=="3"){
            amount+=220*3;}
        }
        if(jCheckBox21.isSelected())
        {
            if(jComboBox21.getSelectedItem()=="1"){
            amount+=170*1;}
         if(jComboBox21.getSelectedItem()=="2"){
            amount+=170*2;}
          if(jComboBox21.getSelectedItem()=="3"){
            amount+=170*3;}
        }
        if(jCheckBox22.isSelected())
        {
            if(jComboBox22.getSelectedItem()=="1"){
            amount+=140*1;}
         if(jComboBox22.getSelectedItem()=="2"){
            amount+=140*2;}
          if(jComboBox22.getSelectedItem()=="3"){
            amount+=140*3;}
        }
        if(jCheckBox23.isSelected())
        {
           if(jComboBox23.getSelectedItem()=="1"){
            amount+=120*1;}
         if(jComboBox23.getSelectedItem()=="2"){
            amount+=120*2;}
          if(jComboBox23.getSelectedItem()=="3"){
            amount+=120*3;}
        }
        if(jCheckBox24.isSelected())
        {
           if(jComboBox24.getSelectedItem()=="1"){
            amount+=180*1;}
         if(jComboBox24.getSelectedItem()=="2"){
            amount+=180*2;}
          if(jComboBox24.getSelectedItem()=="3"){
            amount+=180*3;}
        }

        if(jCheckBox25.isSelected())
        {
            if(jComboBox25.getSelectedItem()=="1"){
            amount+=280*1;}
         if(jComboBox25.getSelectedItem()=="2"){
            amount+=280*2;}
          if(jComboBox25.getSelectedItem()=="3"){
            amount+=280*3;}
        }
        if(jCheckBox26.isSelected())
        {
            if(jComboBox26.getSelectedItem()=="1"){
            amount+=140*1;}
         if(jComboBox26.getSelectedItem()=="2"){
            amount+=140*2;}
          if(jComboBox26.getSelectedItem()=="3"){
            amount+=140*3;}
        }
        if(jCheckBox27.isSelected()){
          if(jComboBox27.getSelectedItem()=="1"){
            amount+=500*1;}
         if(jComboBox27.getSelectedItem()=="2"){
            amount+=500*2;}
          if(jComboBox27.getSelectedItem()=="3"){
            amount+=500*3;}
        }
        if(jCheckBox28.isSelected())
        {
            if(jComboBox28.getSelectedItem()=="1"){
            amount+=200*1;}
         if(jComboBox28.getSelectedItem()=="2"){
            amount+=200*2;}
          if(jComboBox28.getSelectedItem()=="3"){
            amount+=200*3;}
        }
        if(jCheckBox29.isSelected())
        {
            if(jComboBox29.getSelectedItem()=="1"){
            amount+=70*1;}
         if(jComboBox29.getSelectedItem()=="2"){
            amount+=70*2;}
          if(jComboBox29.getSelectedItem()=="3"){
            amount+=70*3;}
        }
        if(jCheckBox30.isSelected())
        {
            if(jComboBox30.getSelectedItem()=="1"){
            amount+=140*1;}
         if(jComboBox30.getSelectedItem()=="2"){
            amount+=140*2;}
          if(jComboBox30.getSelectedItem()=="3"){
            amount+=140*3;}
        }
        javax.swing.JOptionPane.showMessageDialog(null,"IF YOU NEED ANY OTHER MEDICINE \n DON'T WORRY YOU CAN BUY NEAR BY PHARMACY\nTOTAL:"+amount);
        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
setVisible(false);
new Hospital1().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pharm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pharm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pharm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pharm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pharm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JComboBox<String> jComboBox21;
    private javax.swing.JComboBox<String> jComboBox22;
    private javax.swing.JComboBox<String> jComboBox23;
    private javax.swing.JComboBox<String> jComboBox24;
    private javax.swing.JComboBox<String> jComboBox25;
    private javax.swing.JComboBox<String> jComboBox26;
    private javax.swing.JComboBox<String> jComboBox27;
    private javax.swing.JComboBox<String> jComboBox28;
    private javax.swing.JComboBox<String> jComboBox29;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox30;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
